/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SupportedLanguagesShort = "deDE" | "enUS";
export type SupportedLanguages = "de-DE" | "en-US";
export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARNING" | "ERROR";
export type SupportedThemes = "dark" | "light";

/**
 * Schema for config file read by the backend
 */
export interface ConfigFileSchema {
  user: {
    name: string | null;
  } | null;
  settings: {
    databaseUri: string | null;
    language: LanguageData;
    logLevel: LogLevel;
    theme: SupportedThemes;
    yearChangeScrollBegin: boolean;
    yearToShow: null | number;
  };
}
export interface LanguageData {
  dateMask: string;
  importName: SupportedLanguagesShort;
  locale: SupportedLanguages;
  name: string;
  flag: string;
}
