/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SupportedThemes = "dark" | "light";
export type SupportedLanguages = "de-DE" | "en-US";
export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARNING" | "ERROR";

/**
 * Schema for config file read by the backend
 */
export interface ConfigFileSchema {
  user?: {
    name?: string;
  };
  settings?: {
    databaseURI?: string;
    yearToShow?: number;
    theme?: SupportedThemes;
    language?: SupportedLanguages;
    logLevel?: LogLevel;
    todayAutoscrollLeftOffset?: number;
    yearChangeScrollBegin?: boolean;
  };
}
