/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `PublicHolidaysDataSchema`'s JSON-Schema definition
 * via the `patternProperty` "^\d+$".
 */
export type PublicHolidayData = DateBasedHoliday | EasterBasedHoliday;
export type YearlessISODate = string;

/**
 * Schema for public holiday data coming from the backend
 */
export interface PublicHolidaysDataSchema {
  [k: string]: PublicHolidayData;
}
export interface DateBasedHoliday {
  name: string;
  yearlessDate: YearlessISODate;
  easterSundayOffset?: number;
  year?: number;
  /**
   * gets calculated in backend on load from DB
   */
  yearDay?: number;
}
export interface EasterBasedHoliday {
  name: string;
  yearlessDate?: YearlessISODate;
  easterSundayOffset: number;
  year?: number;
  /**
   * gets calculated in backend on load from DB
   */
  yearDay?: number;
}
