/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for users data coming from the backend
 */
export interface UsersDataSchema {
  [k: string]: UserData;
}
/**
 * This interface was referenced by `UsersDataSchema`'s JSON-Schema definition
 * via the `patternProperty` "^\d+$".
 */
export interface UserData {
  name: string;
  workdays: Workdays;
  availableVacationDays: number;
}
export interface Workdays {
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
  saturday: boolean;
  sunday: boolean;
}
