/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ISODate = string;

/**
 * Schema for users data coming from the backend
 */
export interface UsersDataSchema {
  [k: string]: UserData;
}
/**
 * This interface was referenced by `UsersDataSchema`'s JSON-Schema definition
 * via the `patternProperty` "^\d+$".
 */
export interface UserData {
  name: string;
  workdays: Workdays;
  userStats: UserStat;
  vacations: Vacation[];
}
export interface Workdays {
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
  saturday: boolean;
  sunday: boolean;
}
export interface UserStat {
  availableVacationDays: number;
  /**
   * gets calculated in backend on load from DB for current year
   */
  takenVacationDays: number;
  vacationStats: VacationStat[];
}
/**
 * gets calculated in backend on load from DB for current year
 */
export interface VacationStat {
  type: string;
  count: number;
}
export interface Vacation {
  id: number;
  typeId: number;
  start: {
    date: ISODate;
    /**
     * gets calculated in frontend on date selection in form
     */
    yearDay: number;
    /**
     * gets calculated in frontend on date selection in form
     */
    year: number;
  };
  end: {
    date: ISODate;
    /**
     * gets calculated in frontend on date selection in form
     */
    yearDay: number;
    /**
     * gets calculated in frontend on date selection in form
     */
    year: number;
  };
}
