/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for vacation stat data coming from the backend
 */
export interface VacationStatsDataSchema {
  [k: string]: StatsData;
}
/**
 * This interface was referenced by `VacationStatsDataSchema`'s JSON-Schema definition
 * via the `patternProperty` "^\d+$".
 */
export interface StatsData {
  /**
   * gets calculated in backend on load from DB for current year
   */
  calc: {
    takenVacationDays: number;
    vacationStats: VacationStats;
  };
}
/**
 * gets calculated in backend on load from DB for current year
 */
export interface VacationStats {
  /**
   * This interface was referenced by `VacationStats`'s JSON-Schema definition
   * via the `patternProperty` "^\d+$".
   */
  [k: string]: number;
}
