/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ISODate = string;

/**
 * Schema for public holiday data coming from the backend
 */
export interface PublicHolidaysDataSchema {
  [k: string]: PublicHolidayData;
}
/**
 * This interface was referenced by `PublicHolidaysDataSchema`'s JSON-Schema definition
 * via the `patternProperty` "^\d+$".
 */
export interface PublicHolidayData {
  name: string;
  date?: ISODate;
  yearDay: number;
}
