/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ISODate = string;

/**
 * Schema for users data coming from the backend
 */
export interface UsersDataSchema {
  /**
   * This interface was referenced by `UsersDataSchema`'s JSON-Schema definition
   * via the `patternProperty` "^\d+$".
   */
  [k: string]: {
    name: string;
    workdays: Workdays;
    userStats: UserStat;
    vacations: Vacation[];
  };
}
export interface Workdays {
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
  saturday: boolean;
  sunday: boolean;
}
export interface UserStat {
  availableVacationDays: number;
  takenVacationDays: number;
  vacationStats: VacationStat[];
}
export interface VacationStat {
  type: string;
  count: number;
}
export interface Vacation {
  id?: number;
  startDate: ISODate;
  startYearDay: number;
  endDate: ISODate;
  endYearDay: number;
  hexColor: number;
}
