/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ISODate = string;
/**
 * Schema for vacation data coming from the backend
 */
export type VacationDataSchema = UserData[];

export interface UserData {
  id: number;
  name: string;
  userStats: UserStat;
  vacations: Vacation[];
}
export interface UserStat {
  availableVacationDays: number;
  takenVacationDays: number;
  vacationStats: VacationStat[];
}
export interface VacationStat {
  type: string;
  count: number;
}
export interface Vacation {
  id: number;
  startDate: ISODate;
  startYearDay: number;
  endDate: ISODate;
  endYearDay: number;
  hexcolor: number;
}
